version: '3'
services:
  nginx:
    image: 'nginx:alpine'
    volumes:
      - .:/www
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '34888:80'
    networks:
      - network

  dividend-calendar-postgres:
    build:
      context: ./
      dockerfile: ./etc/docker/postgres/Dockerfile
    volumes:
      - .:/www
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dividend-calendar-service
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=0000
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    ports:
      - '5983:5432'
    networks:
      - network

  dividend-calendar-app:
    container_name: dividend-calendar-app
    build:
      context: ./
      dockerfile: ./etc/docker/php-fpm/Dockerfile
    ports:
      - '9511:9000'
    working_dir: /www/
    volumes:
      - .:/www
      - ./logs/php-fpm/:/var/log/php-fpm
    networks:
      - network

  dividend-calendar-redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6134:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network

networks:
    network:
        driver: bridge

